services:
  # === Backend Flask ===
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://hive:hive@metastore-db:5432/metastore
    depends_on:
      - hive-server
    networks:
      - datawarehouse_net

  # === Frontend ===
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - datawarehouse_net

  # === Hadoop Namenode ===
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=datalake
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9870:9870" # Web UI NameNode
      - "8020:8020" # RPC NameNode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - datawarehouse_net

  # === Hadoop Datanode ===
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - SERVICE_PRECONDITION=namenode:8020
    ports:
      - "9864:9864" # Web UI DataNode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      - datawarehouse_net

  # === Hive Metastore DB (Postgres) ===
  metastore-db:
    image: postgres:11
    container_name: metastore-db
    environment:
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
    ports:
      - "5432:5432"
    networks:
      - datawarehouse_net
    volumes:
      - metastore-data:/var/lib/postgresql/data

  # === Hive Metastore Service ===
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    command: /opt/hive/bin/hive #--service metastore
    environment:
      - HIVE_SERVICE=metastore
      - HIVE_METASTORE_DB_TYPE=postgres
      - HIVE_METASTORE_DB_HOST=metastore-db
      - HIVE_METASTORE_DB_NAME=metastore
      - HIVE_METASTORE_DB_USER=hive
      - HIVE_METASTORE_DB_PASSWORD=hive
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - SERVICE_PRECONDITION=metastore-db:5432 namenode:8020
    ports:
      - "9083:9083" # Thrift Metastore
    depends_on:
      - metastore-db
      - namenode
    networks:
      - datawarehouse_net

  # === Hive Server ===
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    command: /opt/hive/bin/hiveserver2
    environment:
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - SERVICE_PRECONDITION=namenode:8020 datanode:9864 hive-metastore:9083
    ports:
      - "10000:10000" # JDBC/Beeline
    depends_on:
      - hive-metastore
      - namenode
      - datanode
    networks:
      - datawarehouse_net

volumes:
  hadoop_namenode:
  hadoop_datanode:
  metastore-data:

networks:
  datawarehouse_net:
    driver: bridge
