services:
  # ---------- APP LAYER ----------
  # nextjs service
  # nextapp:
  #   container_name: nextapp
  #   image: nextapp:1.0.0
  #   build:
  #     context: ./frontend
  #     dockerfile: next.dockerfile
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:4000
  #   depends_on:
  #     - flaskapp

  # flask service
  flaskapp:
    container_name: flaskapp
    image: flaskapp:1.0.0
    build:
      context: ./backend
      dockerfile: flask.dockerfile
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:IoeXFiAnfzgzRbDSmKcOfECJjqChYzyH@mainline.proxy.rlwy.net:21599/railway
      - HIVE_HOST=hive-server
      - HIVE_PORT=10000
    depends_on:
      - db
      - hive-server

  # db service
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: retail_dw
    ports:
      - 5432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - ./data:/data

  # ---------- HADOOP LAYER ----------
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=datalakecluster
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - namenode:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CLUSTER_NAME=datalakecluster
    ports:
      - 9864:9864
    volumes:
      - namenode:/hadoop/dfs/name
    depends_on:
      - namenode

  # ---------- HIVE LAYER ----------
  hive-metastore:
    image: bde2020/hive-metastore:2.3.0-postgresql
    container_name: hive-metastore
    environment:
      - HIVE_LOGLEVEL=INFO
    ports:
      - 9083:9083
    depends_on:
      - namenode

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    environment:
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
    ports:
      - 10000:10000
    depends_on:
      - hive-metastore

volumes:
  pgdata: {}
  namenode: {}
  datanode: {}