services:
  db:
    container_name: retail_datawarehouse
    image: postgres:alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: retail_dw
    ports:
      - 3005:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}