version: "3.8"
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=datalake
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9870:9870"
      - "8020:8020"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - datawarehouse_net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      - datawarehouse_net

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    environment:
      - HIVE_METASTORE_DB_TYPE=postgres
      - HIVE_METASTORE_HOST=metastore-db
      - HIVE_METASTORE_PORT=5432
      - HIVE_METASTORE_DB_NAME=metastore
      - HIVE_METASTORE_USER=hive
      - HIVE_METASTORE_PASSWORD=hive
    ports:
      - "10000:10000"
    depends_on:
      - metastore-db
      - namenode
      - datanode
    networks:
      - datawarehouse_net

  metastore-db:
    build: ./metastore-db
    container_name: metastore-db
    ports:
      - "5432:5432"
    networks:
      - datawarehouse_net

volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  datawarehouse_net:
